server:
  port: 8089
spring:
  application:
    name: "Job Search"
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true
  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
  liquibase:
    change-log: classpath:db/changelog/master.yml
  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.gmail.com
    username: gwinbleid86@gmail.com
    password: "lfxd cbqc tyhf nehe"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
